# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_wxjy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_wxjy.proto',
  package='wlst.pb2',
  syntax='proto3',
  serialized_pb=_b('\n\x13protocol_wxjy.proto\x12\x08wlst.pb2\"L\n\rWxjy_esu_5500\x12\x10\n\x08time_now\x18\x01 \x01(\t\x12\x12\n\x06x_time\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x15\n\tx_voltage\x18\x03 \x03(\x05\x42\x02\x10\x01\"\x8a\x01\n\rWxjy_esu_d700\x12\x12\n\nphase_a_in\x18\x01 \x01(\x05\x12\x12\n\nphase_b_in\x18\x02 \x01(\x05\x12\x12\n\nphase_c_in\x18\x03 \x01(\x05\x12\x13\n\x0bphase_a_out\x18\x04 \x01(\x05\x12\x13\n\x0bphase_b_out\x18\x05 \x01(\x05\x12\x13\n\x0bphase_c_out\x18\x06 \x01(\x05\"\x1f\n\rWxjy_esu_d800\x12\x0e\n\x06status\x18\x01 \x01(\tB\x02H\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WXJY_ESU_5500 = _descriptor.Descriptor(
  name='Wxjy_esu_5500',
  full_name='wlst.pb2.Wxjy_esu_5500',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_now', full_name='wlst.pb2.Wxjy_esu_5500.time_now', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_time', full_name='wlst.pb2.Wxjy_esu_5500.x_time', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='x_voltage', full_name='wlst.pb2.Wxjy_esu_5500.x_voltage', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=109,
)


_WXJY_ESU_D700 = _descriptor.Descriptor(
  name='Wxjy_esu_d700',
  full_name='wlst.pb2.Wxjy_esu_d700',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase_a_in', full_name='wlst.pb2.Wxjy_esu_d700.phase_a_in', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_b_in', full_name='wlst.pb2.Wxjy_esu_d700.phase_b_in', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_c_in', full_name='wlst.pb2.Wxjy_esu_d700.phase_c_in', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_a_out', full_name='wlst.pb2.Wxjy_esu_d700.phase_a_out', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_b_out', full_name='wlst.pb2.Wxjy_esu_d700.phase_b_out', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_c_out', full_name='wlst.pb2.Wxjy_esu_d700.phase_c_out', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=250,
)


_WXJY_ESU_D800 = _descriptor.Descriptor(
  name='Wxjy_esu_d800',
  full_name='wlst.pb2.Wxjy_esu_d800',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='wlst.pb2.Wxjy_esu_d800.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=283,
)

DESCRIPTOR.message_types_by_name['Wxjy_esu_5500'] = _WXJY_ESU_5500
DESCRIPTOR.message_types_by_name['Wxjy_esu_d700'] = _WXJY_ESU_D700
DESCRIPTOR.message_types_by_name['Wxjy_esu_d800'] = _WXJY_ESU_D800

Wxjy_esu_5500 = _reflection.GeneratedProtocolMessageType('Wxjy_esu_5500', (_message.Message,), dict(
  DESCRIPTOR = _WXJY_ESU_5500,
  __module__ = 'protocol_wxjy_pb2'
  # @@protoc_insertion_point(class_scope:wlst.pb2.Wxjy_esu_5500)
  ))
_sym_db.RegisterMessage(Wxjy_esu_5500)

Wxjy_esu_d700 = _reflection.GeneratedProtocolMessageType('Wxjy_esu_d700', (_message.Message,), dict(
  DESCRIPTOR = _WXJY_ESU_D700,
  __module__ = 'protocol_wxjy_pb2'
  # @@protoc_insertion_point(class_scope:wlst.pb2.Wxjy_esu_d700)
  ))
_sym_db.RegisterMessage(Wxjy_esu_d700)

Wxjy_esu_d800 = _reflection.GeneratedProtocolMessageType('Wxjy_esu_d800', (_message.Message,), dict(
  DESCRIPTOR = _WXJY_ESU_D800,
  __module__ = 'protocol_wxjy_pb2'
  # @@protoc_insertion_point(class_scope:wlst.pb2.Wxjy_esu_d800)
  ))
_sym_db.RegisterMessage(Wxjy_esu_d800)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
_WXJY_ESU_5500.fields_by_name['x_time'].has_options = True
_WXJY_ESU_5500.fields_by_name['x_time']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_WXJY_ESU_5500.fields_by_name['x_voltage'].has_options = True
_WXJY_ESU_5500.fields_by_name['x_voltage']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
