# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol_tp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protocol_wxjy_pb2 as protocol__wxjy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol_tp.proto',
  package='wlst.pb2',
  syntax='proto3',
  serialized_pb=_b('\n\x11protocol_tp.proto\x12\x08wlst.pb2\x1a\x13protocol_wxjy.proto\"\xc6\x01\n\x04Wxjy\x12.\n\rwxjy_esu_5500\x18\x01 \x01(\x0b\x32\x17.wlst.pb2.Wxjy_esu_5500\x12.\n\rwxjy_esu_d500\x18\x02 \x01(\x0b\x32\x17.wlst.pb2.Wxjy_esu_5500\x12.\n\rwxjy_esu_d700\x18\x03 \x01(\x0b\x32\x17.wlst.pb2.Wxjy_esu_d700\x12.\n\rwxjy_esu_d800\x18\x04 \x01(\x0b\x32\x17.wlst.pb2.Wxjy_esu_d800B\x02H\x01\x62\x06proto3')
  ,
  dependencies=[protocol__wxjy__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WXJY = _descriptor.Descriptor(
  name='Wxjy',
  full_name='wlst.pb2.Wxjy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wxjy_esu_5500', full_name='wlst.pb2.Wxjy.wxjy_esu_5500', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wxjy_esu_d500', full_name='wlst.pb2.Wxjy.wxjy_esu_d500', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wxjy_esu_d700', full_name='wlst.pb2.Wxjy.wxjy_esu_d700', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wxjy_esu_d800', full_name='wlst.pb2.Wxjy.wxjy_esu_d800', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=251,
)

_WXJY.fields_by_name['wxjy_esu_5500'].message_type = protocol__wxjy__pb2._WXJY_ESU_5500
_WXJY.fields_by_name['wxjy_esu_d500'].message_type = protocol__wxjy__pb2._WXJY_ESU_5500
_WXJY.fields_by_name['wxjy_esu_d700'].message_type = protocol__wxjy__pb2._WXJY_ESU_D700
_WXJY.fields_by_name['wxjy_esu_d800'].message_type = protocol__wxjy__pb2._WXJY_ESU_D800
DESCRIPTOR.message_types_by_name['Wxjy'] = _WXJY

Wxjy = _reflection.GeneratedProtocolMessageType('Wxjy', (_message.Message,), dict(
  DESCRIPTOR = _WXJY,
  __module__ = 'protocol_tp_pb2'
  # @@protoc_insertion_point(class_scope:wlst.pb2.Wxjy)
  ))
_sym_db.RegisterMessage(Wxjy)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
